
server:
  servlet:
    context-path: /uzitec/api
springdoc:
  swagger-ui:
    path: /public/swagger

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/uzitec
    username: postgres
    password: admin
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false